[versions]
junit-jupiter = "5.12.1"
sqlite = "3.51.1.0"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
